var dirlist = `
examples/3d/3dGraphicsEngine/images/128x128.png
examples/3d/3dGraphicsEngine/meshes/caveCritter.txt
examples/3d/3dGraphicsEngine/meshes/caveCritterWalk1.txt
examples/3d/3dGraphicsEngine/meshes/caveCritterWalk2.txt
examples/3d/asteroids3D/images/console.png
examples/3d/asteroids3D/images/lights_0.png
examples/3d/asteroids3D/images/lights_1.png
examples/3d/asteroids3D/images/lights_2.png
examples/3d/asteroids3D/images/onfire.png
examples/3d/asteroids3D/images/radar.png
examples/3d/asteroids3D/images/reticle.png
examples/3d/asteroids3D/images/shipicon.png
examples/3d/asteroids3D/images/spacehud.png
examples/3d/asteroids3D/images/sweep.png
examples/3d/asteroids3D/meshes/asteroid.obj
examples/3d/asteroids3D/meshes/cone.obj
examples/3d/asteroids3D/meshes/engines.obj
examples/3d/asteroids3D/meshes/fire.obj
examples/3d/asteroids3D/meshes/hull.obj
examples/3d/asteroids3D/meshes/spaceship.x
examples/3d/asteroids3D/meshes/sphere.x
examples/3d/asteroids3D/meshes/window.obj
examples/3d/asteroids3D/meshes/wings.obj
examples/3d/raycasting/images/sciFiWalls.png
examples/3d/wiremesh/cube.obj
examples/3d/wiremesh/meshes/base.obj
examples/3d/wiremesh/meshes/box.x
examples/3d/wiremesh/meshes/boxPoly.x
examples/3d/wiremesh/meshes/cube.obj
examples/3d/wiremesh/meshes/gun.obj
examples/3d/wiremesh/meshes/spaceship.x
examples/3d/wiremesh/meshes/sphere.x
examples/3d/wiremesh/meshes/tank.obj
examples/3d/wiremesh/meshes/turret.obj
examples/drawing/cellularAutomaton/images/poster1.jpg
examples/drawing/cellularAutomaton/images/poster1_after.png
examples/drawing/cellularAutomaton/images/poster1_mask.png
examples/drawing/cellularAutomaton/images/poster1_mask2.png
examples/eventDriven/spaceBoss/images/background.jpg
examples/eventDriven/spaceBoss/images/bbullet.png
examples/eventDriven/spaceBoss/images/bullet.png
examples/eventDriven/spaceBoss/images/crown.png
examples/eventDriven/spaceBoss/images/dbbullet.png
examples/eventDriven/spaceBoss/images/enginefire.png
examples/eventDriven/spaceBoss/images/eship.png
examples/eventDriven/spaceBoss/images/gbullet.png
examples/eventDriven/spaceBoss/images/head.png
examples/eventDriven/spaceBoss/images/headfireeyes.png
examples/eventDriven/spaceBoss/images/lightening.png
examples/eventDriven/spaceBoss/images/mouth.png
examples/eventDriven/spaceBoss/images/mouthAngry.png
examples/eventDriven/spaceBoss/images/mouthOpen.png
examples/eventDriven/spaceBoss/images/mouthTop.png
examples/eventDriven/spaceBoss/images/pbullet.png
examples/eventDriven/spaceBoss/images/player.png
examples/eventDriven/spaceBoss/images/rbullet.png
examples/eventDriven/spaceBoss/images/rfistclosed.png
examples/eventDriven/spaceBoss/images/rhandflat.png
examples/eventDriven/spaceBoss/images/rOpenHand.png
examples/eventDriven/spaceBoss/images/rOpenHandEye.png
src/sharedMedia/images/anim/butterfly-a.png
src/sharedMedia/images/anim/butterfly-b.png
src/sharedMedia/images/dialog.png
src/sharedMedia/images/dialog_asteroids.png
src/sharedMedia/images/garage/background.jpg
src/sharedMedia/images/garage/crate.png
src/sharedMedia/images/garage/run.png
src/sharedMedia/images/garage/run2.png
src/sharedMedia/images/garage/tire.png
src/sharedMedia/images/road/background.jpg
src/sharedMedia/images/road/car1.png
src/sharedMedia/images/road/car2.png
src/sharedMedia/images/solarsystem/background.jpg
src/sharedMedia/images/solarsystem/p1.png
src/sharedMedia/images/solarsystem/p2.png
src/sharedMedia/images/solarsystem/p3.png
src/sharedMedia/images/solarsystem/sun.png
`;
